dataset: 'coil20'
architecture: 'mnist_model_dropout'
max_steps: 6000

learning_rate: [0.001, 0.0005, 0.0001]
warmup_steps: [1, 1000]
unsup_batch_size: [50, 100, 200]
visit_weight_base: [0.3, 0.7]
l1_weight: [0, 0.00001]
reg_warmup_steps: [1,1000]