dataset: 'mnist'
logdir: '/work/plapp/logs'
l1_weight: 0
warmup_steps: 2000
reg_warmup_steps: 1000
norm_weight:  0.00001
num_augmented_samples: 4
visit_weight_base: 0.8
learning_rate: 0.0008
init_with_kmeans: True
max_steps: 12000
unsup_batch_size: 100
reg_association_weight: 0.9
reg_decay_factor: 0.3            # reduce reg weight after kmeans init

trafo_weight: 2e-5
trafo_separate_loss_collection: True