dataset: 'mnist'
architecture: 'resnet_mnist_model_d'
max_steps: 17000
decay_steps: 5000
l1_weight: 0
norm_weight: [0.0001,0.00001]
init_with_kmeans: True
num_augmented_samples: 3


# general  : 24 combinations
learning_rate: [0.001, 0.0003, 0.0001]
warmup_steps: [1000, 2000]
unsup_batch_size: 100
num_blocks: [2,3]                # blocks in resnet
dropout_keep_prob: [0.5,0.6,0.8, 1]           # most reliable results
emb_size: [64,128]

# optimizer:  4 combination
beta1: [0.6,0.8,0.9]
beta2: [0.9,0.99, 0.999]

# centroid associations: 2
visit_weight_base: [0.5, 1.0]

# augmentation associations: 2
reg_decay_factor: [0.2,0.4]            # reduce reg weight after kmeans init
reg_warmup_steps: [1000,1500,2000]
