dataset: 'mnist'
architecture: 'resnet_mnist_model'
logdir: '/work/plapp/logs'
l1_weight: 0
warmup_steps: 2000
reg_warmup_steps: 1000
visit_weight_base: 1
learning_rate: 0.0008
init_with_kmeans: True
emb_size: 64
max_steps: 12000
reg_association_weight: 0.9