dataset: 'svhn'
architecture: 'resnet_mnist_model'
max_steps: 50000
decay_steps: 15000
l1_weight: 0
norm_weight:  0.00001
init_with_kmeans: True
num_augmented_samples: 4
num_unlabeled_images: 150000
logdir: '/efs/svhn'


# general  : 24 combinations
learning_rate: 0.0008
warmup_steps: 4000
unsup_batch_size: 150
num_blocks: 5                # blocks in resnet
dropout_keep_prob: 1           # most reliable results
emb_size: 64

beta1: 0.6
beta2: 0.9

visit_weight_base: 0.2

reg_decay_factor: 0.2            # reduce reg weight after kmeans init
reg_warmup_steps: 7000


# centroid associations: 2
cluster_association_weight: [0,1e-7, 1e-5,1e-3, 0.1,0.6,1]

# augmentation associations: 2
reg_association_weight: [0,1e-7, 1e-5,1e-3, 0.1,0.6,1]

# cluster hardening: 3
cluster_hardening_weight: [0,1e-7, 1e-5, 1e-3, 1e-1, 0.3,1]

# logit entropy: 3
logit_entropy_weight: [0,1e-7, 1e-5, 1e-3, 1e-1, 0.3,1]

# transformation loss: 3
trafo_weight: [0,1e-7, 1e-5, 1e-3, 1e-1, 0.3,1]
