dataset: 'svhn'
architecture: ['resnet_cifar_model','resnet_mnist_model']
max_steps: 23000
decay_steps: [6000,7000,8000,9000,10000]
l1_weight: 0
norm_weight: [0.0001, 0.00005, 0.00001,0.000005]
init_with_kmeans: True
num_augmented_samples: [3,4,5]
num_unlabeled_images: [0,50000,100000]
logdir: '/work/plapp/logs'


# general  : 24 combinations
learning_rate: [0.001, 0.001, 0.0008, 0.0005]
warmup_steps: [1000,2000,4000]
unsup_batch_size: [100,130,150,200]
num_blocks: [3,5]                # blocks in resnet
dropout_keep_prob: [0.6,0.7,0.8,1]           # most reliable results
emb_size: 64

# optimizer:  4 combination
beta1: [0.6,0.8]
beta2: [0.9,0.99]

# centroid associations: 2
visit_weight_base: [0.05,0.1,0.3,0.5,0.7,0.8]

# augmentation associations: 2
reg_decay_factor: [0.2,0.4,0.6,0.8]            # reduce reg weight after kmeans init
reg_warmup_steps: [1000,1500,2000,2500,3000,3500,4000,4500,5000,6000,7000]
