dataset: 'mnist'
logdir: '/work/plapp/logs'
l1_weight: 0
warmup_steps: 2000
reg_warmup_steps: 10   # no need for this
visit_weight_base: 0.8
learning_rate: 0.0008
norm_weight:  0.00001
num_augmented_samples: 4
init_with_kmeans: True
max_steps: 23000
decay_steps: 10000
unsup_batch_size: 100
reg_association_weight: 0
cluster_association_weight: 1

trafo_weight: 0

scale_match_ab: 1
norm_target: 1

